name: Compile SCSS to CSS

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install -g sass

      - name: Compile and Minify SCSS to CSS
        run: |
          sass scss/styles.scss css/styles.css --style=compressed

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add css/styles.css
          git commit -m "Compiled and minified SCSS to CSS [skip ci]" || echo "No changes to commit"
          git push
